# Generated by Django 2.2.1 on 2019-06-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works', models.BooleanField(default=True)),
                ('repeat_counter', models.PositiveIntegerField()),
                ('power_from_network', models.BooleanField(default=True)),
            ],
        ),
    ]
